### ISSUE TITLE
Shift method no longer working

### ISSUE THREAD

**Issue by andreytierra** [ExodusMovement/shapeshift.io#4]
It comes back with the response: 
{
    "message": "You must be logged in with a verified user"
}

Is this part of the shapeshit.io move to membership program based services?

**Comment by srirachaweaksauce** [comment]
Hey @andreytierra, we recently changed some things with the ShapeShift system to require an account in order to use ShapeShift. If you are interested in getting an Oauth client and secret so you can integrate, we can help you out via our partner team - https://info.shapeshift.io/become-a-partner/

It should be said that it is likely that this library doesn't support Oauth yet, however all of our Oauth docs are here: https://docs.shapeshift.io
